from environs import Env

env = Env()
env.read_env()

TEST_TOKEN = env('TEST_TOKEN')
TOKEN = env('TOKEN')

# Wit.ai
EN_SERVER_ACCESS_TOKEN = env('EN_SERVER_ACCESS_TOKEN')
WIT_AI_API_ENDPOINT = env('WIT_AI_API_ENDPOINT')
RU_SERVER_ACCESS_TOKEN = env('RU_SERVER_ACCESS_TOKEN')
UA_SERVER_ACCESS_TOKEN = env('UA_SERVER_ACCESS_TOKEN')
